customCommands:
  - key: "C"
    context: "files"
    command: "lc draft | pbcopy && pbpaste"
    loadingText: "Generating commit message..."
    outputTitle: "Message Generated"
    output: popup
  - key: "M"
    context: "files"
    command: "pbpaste | git commit -F -"
    prompts:
      - type: "confirm"
        title: "Commit with this message?"
        body: '{{ runCommand "pbpaste" }}'

gui:
  showBottomLine: false
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#6EA3FE"
      - "bold"
    inactiveBorderColor:
      - "#A7B1D9"
    searchingActiveBorderColor:
      - "#ff9e64"
      - "bold"
    optionsTextColor:
      - "#7aa2f7"
    selectedLineBgColor:
      - "#283457"
    cherryPickedCommitFgColor:
      - "#7aa2f7"
    cherryPickedCommitBgColor:
      - "#bb9af7"
    markedBaseCommitFgColor:
      - "#7aa2f7"
    markedBaseCommitBgColor:
      - "#e0af68"
    unstagedChangesColor:
      - "#db4b4b"
    defaultFgColor:
      - "#c0caf5"
