customCommands:
  - key: 'C'
    context: 'files'
    command: 'lumen -p openrouter -m "google/gemini-2.5-flash-lite-preview-06-17" draft | git commit -F -'
    loadingText: 'Generating message...'
    outputTitle: 'Auto Commit'
    output: popup

gui:
  showBottomLine: false
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#6EA3FE"
      - "bold"
    inactiveBorderColor:
      - "#A7B1D9"
    searchingActiveBorderColor:
      - "#ff9e64"
      - "bold"
    optionsTextColor:
      - "#7aa2f7"
    selectedLineBgColor:
      - "#283457"
    cherryPickedCommitFgColor:
      - "#7aa2f7"
    cherryPickedCommitBgColor:
      - "#bb9af7"
    markedBaseCommitFgColor:
      - "#7aa2f7"
    markedBaseCommitBgColor:
      - "#e0af68"
    unstagedChangesColor:
      - "#db4b4b"
    defaultFgColor:
      - "#c0caf5"

