customCommands:
  - key: 'C'
    context: 'files'
    command: 'lumen -p openrouter -m "google/gemini-2.5-flash-lite-preview-06-17" draft | git commit -F -'
    loadingText: 'Generating message...'
    outputTitle: 'Auto Commit'
    output: popup
