customCommands:
  - key: "C"
    context: "files"
    prompts:
      - type: "input"
        key: "Msg"
        title: "Commit message:"
        initialValue: '{{ runCommand "sh -c \"output=$(lc draft 2>&1); if echo \\\"$output\\\" | grep -q \\\"error:\\\"; then echo \\\"\\\"; else echo \\\"$output\\\"; fi\"" }}'
    command: 'if git diff --cached --quiet; then echo "No staged changes to commit"; exit 1; else git commit -m "{{.Form.Msg}}"; fi'

gui:
  showBottomLine: false
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#6EA3FE"
      - "bold"
    inactiveBorderColor:
      - "#A7B1D9"
    searchingActiveBorderColor:
      - "#ff9e64"
      - "bold"
    optionsTextColor:
      - "#7aa2f7"
    selectedLineBgColor:
      - "#283457"
    cherryPickedCommitFgColor:
      - "#7aa2f7"
    cherryPickedCommitBgColor:
      - "#bb9af7"
    markedBaseCommitFgColor:
      - "#7aa2f7"
    markedBaseCommitBgColor:
      - "#e0af68"
    unstagedChangesColor:
      - "#db4b4b"
    defaultFgColor:
      - "#c0caf5"
