customCommands:
  - key: "<c-l>"
    context: "files"
    command: "lumen draft | tee >(pbcopy)"
    loadingText: "Generating message..."
    showOutput: true
  - key: "<c-k>"
    context: "files"
    command: "lumen draft -c {{.Form.Context | quote}} | tee >(pbcopy)"
    loadingText: "Generating message..."
    showOutput: true
    prompts:
      - type: "input"
        title: "Context"
        key: "Context"
