customCommands:
  - key: "C"
    context: "files"
    command: |
      bash -c '
      msg=$(lc draft)
      echo "Commit message:"
      echo "==============="
      echo "$msg"
      echo "==============="
      echo
      echo "Press ENTER to commit, ESC to cancel"
      read -n 1 -s key
      if [ "$key" = "" ]; then
        echo
        echo "Committing..."
        echo "$msg" | git commit -F -
        echo "Done!"
      else
        echo
        echo "Cancelled"
        exit 1
      fi
      '
    loadingText: "Generating message..."
    outputTitle: "Commit with Confirmation"
    output: popup

gui:
  showBottomLine: false
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#6EA3FE"
      - "bold"
    inactiveBorderColor:
      - "#A7B1D9"
    searchingActiveBorderColor:
      - "#ff9e64"
      - "bold"
    optionsTextColor:
      - "#7aa2f7"
    selectedLineBgColor:
      - "#283457"
    cherryPickedCommitFgColor:
      - "#7aa2f7"
    cherryPickedCommitBgColor:
      - "#bb9af7"
    markedBaseCommitFgColor:
      - "#7aa2f7"
    markedBaseCommitBgColor:
      - "#e0af68"
    unstagedChangesColor:
      - "#db4b4b"
    defaultFgColor:
      - "#c0caf5"
