command_timeout = 5000  # Timeout in milliseconds

format = """
[](#a3aed2)\
$os$hostname\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$nodejs\
$rust\
$php\
[](fg:#212736 bg:#1d2230)\
$time\
\n$character"""

add_newline = true

[os]
disabled = false
style = "bg:#a3aed2 fg:#090c0c"
format = '[$symbol]($style)'

[os.symbols]
Windows = " "
Ubuntu = " "
SUSE = " "
Raspbian = " "
RedHatEnterprise = " "
Mint = " "
Linux = " "
Gentoo = " "
Fedora = " "
Debian = " "
Arch = " "
Alpine = " "
Amazon = " "
Android = " "
Macos = " "

[hostname]
ssh_only = false
style = "bg:#a3aed2 fg:#090c0c"
format = "[ $hostname ]($style)"
disabled = false

[directory]
style = "fg:#212736 bg:#7AA2F7"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Developer" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
format ="[$all_status[$ahead_behind](fg:#dddddd bg:#394260)]($style)"
# format = "[[$conflicted](yellow bg:#394260)($untracked$modified$renamed)[$staged](green bg:#394260)[$deleted](red bg:#394260)($stashed)[$ahead_behind](fg:#dddddd bg:#394260)]($style)"
conflicted = "[ $count ](yellow bg:#394260)"
staged = "[ $count ](green bg:#394260)"
deleted = "[ $count ](red bg:#394260)"
untracked = " $count "
modified = " $count "
renamed = " $count "
stashed = "󰓏 $count "
up_to_date = "[  ](green bg:#394260)"
ahead = "[󰁝$count](yellow bg:#394260) "
behind = "[󰁅$count](green bg:#394260) "
diverged = "[󰁝$ahead_count](yellow bg:#394260) [󰁅${behind_count}](green bg:#394260) "
style = "fg:#a0a9cb bg:#394260"

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#333844"
format = '[[  $time ](fg:#a0a9cb bg:#333844)]($style)'

[character]
disabled = false
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'
vimcmd_symbol = '[❚](bold grey)'

[line_break]
disabled = false
